insert into public.store_settings (id, store_name, support_email, currency, order_prefix, automation)
values (
  'default',
  'Zhua Enterprises',
  'hello@zhuaenterprises.co.za',
  'ZAR',
  'ZE-2026',
  '{"autoConfirmPayments": false, "lowStockAlerts": true, "reviewModerationQueue": true}'::jsonb
)
on conflict (id) do update
set
  store_name = excluded.store_name,
  support_email = excluded.support_email,
  currency = excluded.currency,
  order_prefix = excluded.order_prefix,
  automation = excluded.automation;

insert into public.content_blocks (title, route, status, payload)
values
  (
    'Homepage Hero Campaign',
    '/',
    'published',
    '{"headline":"South Africa''s Premium Home Solutions Platform","cta":"Shop Bestsellers","supportingCopy":"Curated furniture, custom curtains, and interior design services delivered across all provinces."}'::jsonb
  ),
  (
    'Winter Curtain Promo',
    '/shop/curtains',
    'scheduled',
    '{"headline":"Winter Texture Drop","cta":"Explore Curtains"}'::jsonb
  ),
  (
    'Design Studio Feature Strip',
    '/design-studio',
    'published',
    '{"headline":"Design Studio","cta":"Open Design Studio"}'::jsonb
  ),
  (
    'Checkout Trust Notes',
    '/checkout',
    'draft',
    '{"headline":"Secure Checkout","copy":"PCI aligned processing and trusted local support."}'::jsonb
  )
on conflict do nothing;

insert into public.products (
  slug,
  name,
  category,
  subcategory,
  price_cents,
  original_price_cents,
  rating,
  review_count,
  badge,
  description,
  long_description,
  images,
  colors,
  sizes,
  fabrics,
  in_stock,
  is_customizable,
  delivery_days,
  features,
  stock,
  sku,
  status
)
values
  (
    'oslo-sectional-sofa',
    'Oslo Sectional Sofa',
    'furniture',
    'Sofas & Lounges',
    2499900,
    3200000,
    4.8,
    124,
    'sale',
    'Premium L-shaped sectional with deep-seated comfort and modular configuration.',
    'The Oslo Sectional is the centrepiece your living room deserves. Crafted with kiln-dried hardwood frame and wrapped in premium Italian boucle fabric, this sofa is built to last a lifetime.',
    '["/images/sofa-1.jpg","/images/sofa-2.jpg","/images/sofa-3.jpg"]'::jsonb,
    '[{"name":"Stone Boucle","hex":"#C8BCA8"},{"name":"Mocha Velvet","hex":"#6B4F3A"},{"name":"Slate Blue","hex":"#5A6E8A"},{"name":"Forest Green","hex":"#3D5A4A"}]'::jsonb,
    array['2-Seater','3-Seater','L-Shape','U-Shape'],
    array[]::text[],
    true,
    true,
    '14-21 business days',
    array['Kiln-dried hardwood frame','Italian boucle fabric','Modular configuration','5-year structural warranty'],
    14,
    'ZH-FUR-OSL-01',
    'active'
  ),
  (
    'nordic-dining-table',
    'Nordic Dining Table',
    'furniture',
    'Dining',
    1850000,
    null,
    4.9,
    87,
    'new',
    'Solid white oak dining table with natural grain detail and blackened steel legs.',
    'The Nordic Dining Table brings Scandinavian minimalism to your dining space.',
    '["/images/table-1.jpg","/images/table-2.jpg"]'::jsonb,
    '[{"name":"Natural Oak","hex":"#C8A96E"},{"name":"Smoked Oak","hex":"#72614A"},{"name":"Whitewash","hex":"#EDE8DC"}]'::jsonb,
    array['6-Seater (180cm)','8-Seater (220cm)','10-Seater (260cm)'],
    array[]::text[],
    true,
    false,
    '10-14 business days',
    array['Solid white oak','Blackened steel legs','Food-safe oil finish','Seats 6-10'],
    6,
    'ZH-FUR-NDT-02',
    'active'
  ),
  (
    'sahara-eyelet-curtains',
    'Sahara Eyelet Curtains',
    'curtains',
    'Block-Out Curtains',
    320000,
    null,
    4.7,
    203,
    'bestseller',
    'Premium block-out curtains in rich desert tones. Available custom to any dimension.',
    'The Sahara Eyelet Curtains offer 100% light blocking performance without compromising on style.',
    '["/images/curtain-1.jpg","/images/curtain-2.jpg"]'::jsonb,
    '[{"name":"Desert Sand","hex":"#C4A882"},{"name":"Rust Terracotta","hex":"#B85C38"},{"name":"Sage Green","hex":"#7A9E7E"},{"name":"Stone Grey","hex":"#8B8B8B"},{"name":"Midnight Navy","hex":"#2C3E6B"}]'::jsonb,
    array[]::text[],
    array['Linen Blend','Velvet','Sheer','Block-Out'],
    true,
    true,
    '7-10 business days',
    array['100% light blocking','Thermal lining','Custom dimensions','Machine washable'],
    28,
    'ZH-CUR-SEY-03',
    'active'
  ),
  (
    'wave-sheer-panels',
    'Wave Sheer Panels',
    'curtains',
    'Sheer Curtains',
    180000,
    null,
    4.6,
    156,
    'new',
    'Flowing wave-headed sheers for a soft, modern look in any room.',
    'The Wave Sheer Panels create a beautiful, flowing effect when drawn.',
    '["/images/sheer-1.jpg","/images/sheer-2.jpg"]'::jsonb,
    '[{"name":"Pure White","hex":"#F5F5F0"},{"name":"Warm Cream","hex":"#F0E8D5"},{"name":"Blush","hex":"#E8C4B8"}]'::jsonb,
    array[]::text[],
    array['Voile','Linen Sheer','Chiffon'],
    true,
    true,
    '5-8 business days',
    array['S-fold wave heading','UV protection','Machine washable','Custom widths'],
    32,
    'ZH-CUR-WSP-04',
    'draft'
  ),
  (
    'luxe-roller-blind',
    'Luxe Roller Blind',
    'curtains',
    'Roller Blinds',
    95000,
    120000,
    4.8,
    312,
    'sale',
    'Clean, modern roller blind with whisper-quiet mechanism and precision fit.',
    'The Luxe Roller Blind delivers clean lines and precision control.',
    '["/images/blind-1.jpg","/images/blind-2.jpg"]'::jsonb,
    '[{"name":"White","hex":"#FFFFFF"},{"name":"Pearl Grey","hex":"#C8C8C8"},{"name":"Cappuccino","hex":"#C4A882"},{"name":"Charcoal","hex":"#3A3530"}]'::jsonb,
    array[]::text[],
    array[]::text[],
    true,
    true,
    '5-7 business days',
    array['Whisper-quiet mechanism','UV-resistant fabric','Motorisation available','Custom cut'],
    45,
    'ZH-CUR-LRB-05',
    'active'
  ),
  (
    'palazzo-bed-frame',
    'Palazzo Bed Frame',
    'furniture',
    'Bedroom',
    1580000,
    null,
    4.9,
    67,
    'new',
    'Statement upholstered bed frame with tufted headboard and solid wood base.',
    'The Palazzo Bed Frame makes a statement without saying a word.',
    '["/images/bed-1.jpg","/images/bed-2.jpg"]'::jsonb,
    '[{"name":"Champagne Velvet","hex":"#C8A96E"},{"name":"Deep Teal","hex":"#1B4F5E"},{"name":"Blush Rose","hex":"#C48B8B"},{"name":"Graphite","hex":"#4A4A4A"}]'::jsonb,
    array['Queen (152cm)','King (183cm)','Super King (200cm)'],
    array[]::text[],
    true,
    true,
    '14-21 business days',
    array['Performance velvet','Solid wood base','Tufted headboard','20-year frame warranty'],
    9,
    'ZH-FUR-PBF-06',
    'active'
  ),
  (
    'arco-floor-lamp',
    'Arco Arc Floor Lamp',
    'accessories',
    'Lighting',
    420000,
    null,
    4.7,
    45,
    null,
    'Sculptural arc lamp with marble base and brushed brass finish.',
    'The Arco Arc Floor Lamp is a design classic reimagined.',
    '["/images/lamp-1.jpg","/images/lamp-2.jpg"]'::jsonb,
    '[{"name":"Brass + White Marble","hex":"#C9A84C"},{"name":"Matte Black + Black Marble","hex":"#1A1A1A"}]'::jsonb,
    array[]::text[],
    array[]::text[],
    true,
    false,
    '5-8 business days',
    array['Natural marble base','Brushed brass finish','LED compatible','Adjustable arc'],
    9,
    'ZH-ACC-AFL-07',
    'active'
  ),
  (
    'atlas-coffee-table',
    'Atlas Coffee Table',
    'furniture',
    'Living Room',
    890000,
    null,
    4.8,
    93,
    'bestseller',
    'Travertine-top coffee table with blackened steel base - artful and functional.',
    'The Atlas Coffee Table is a statement piece for the modern living room.',
    '["/images/coffee-table-1.jpg","/images/coffee-table-2.jpg"]'::jsonb,
    '[{"name":"Ivory Travertine","hex":"#E8DCC8"},{"name":"Walnut + Brass","hex":"#6B4F2A"}]'::jsonb,
    array['Small (90cm)','Medium (120cm)','Large (150cm)'],
    array[]::text[],
    true,
    false,
    '7-10 business days',
    array['Natural travertine','Blackened steel base','Sealing included','Unique grain pattern'],
    0,
    'ZH-FUR-ACT-08',
    'archived'
  )
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  price_cents = excluded.price_cents,
  original_price_cents = excluded.original_price_cents,
  rating = excluded.rating,
  review_count = excluded.review_count,
  badge = excluded.badge,
  description = excluded.description,
  long_description = excluded.long_description,
  images = excluded.images,
  colors = excluded.colors,
  sizes = excluded.sizes,
  fabrics = excluded.fabrics,
  in_stock = excluded.in_stock,
  is_customizable = excluded.is_customizable,
  delivery_days = excluded.delivery_days,
  features = excluded.features,
  stock = excluded.stock,
  sku = excluded.sku,
  status = excluded.status;

delete from public.gallery_items;

insert into public.gallery_items (
  title,
  location,
  project,
  before_image,
  after_image,
  status,
  display_order
)
values
  (
    'Sandton Lounge Refresh',
    'Johannesburg, GP',
    'Living Room Renovation',
    '{"publicId":"zhua/gallery/sandton-before","secureUrl":"https://res.cloudinary.com/demo/image/upload/v1/sample","alt":"Sandton lounge before makeover"}'::jsonb,
    '{"publicId":"zhua/gallery/sandton-after","secureUrl":"https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/nature-mountains","alt":"Sandton lounge after makeover"}'::jsonb,
    'published',
    1
  ),
  (
    'Cape Town Master Suite',
    'Cape Town, WC',
    'Master Bedroom Curtains',
    null,
    null,
    'draft',
    2
  );

delete from public.testimonials;

insert into public.testimonials (
  name,
  location,
  rating,
  text,
  project,
  avatar_image,
  before_image,
  after_image,
  status,
  display_order
)
values
  (
    'Naledi Mokoena',
    'Johannesburg, GP',
    5,
    'Zhua transformed our living room completely. The Oslo sofa is even more stunning in person, and the installation team was professional and on time.',
    'Living Room Renovation',
    null,
    null,
    null,
    'published',
    1
  ),
  (
    'Pieter van der Berg',
    'Cape Town, WC',
    5,
    'The curtain customizer made the selection process easy and the final fit was perfect. Delivery was ahead of schedule too.',
    'Master Bedroom Curtains',
    null,
    null,
    null,
    'published',
    2
  );
